pipeline {
    agent any

         stages {
            stage ('Execue Unit test') {
                     parallel {
                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    environment {
                        HOME = "${WORKSPACE}"
                        GOPATH = "${WORKSPACE}/.go"
                        GOMODCACHE = "${WORKSPACE}/.go/pkg/mod"
                        XDG_CACHE_HOME = "${WORKSPACE}/.cache"
                        GOCACHE = "${WORKSPACE}/.cache/go-build"
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh '''
                            mkdir -p "$GOPATH" "$GOMODCACHE" "$XDG_CACHE_HOME" "$GOCACHE"
                            go test ./... -v 2>&1 | go-junit-report -set-exit-code > report.xml
                            go test ./... -covermode=atomic -coverprofile=coverage.out
                            go tool cover -html=coverage.out -o coverage.html
                            mkdir -p reports
                            mv coverage.html reports/
                            '''
                        }
                    }
                    post {
                        always {
                            junit 'bugtracker-backend/report.xml'
                            publishHTML target: [
                                reportDir: 'bugtracker-backend/reports',
                                reportFiles: 'coverage.html',
                                reportName: 'Backend Coverage Report'
                            ]
                        }
                    }
                }

                 stage('Unit Tests - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh '''
                    npm ci
                    npm test
                    '''
                }
            }
            post {
                always {
                    junit 'bugtracker-frontend/test-results.xml'
                }
                }
              }

              stage ('Launch Application') {
                agent {
                    docker{
                        image 'docker:27-cli'
                        alwaysPull true
                        reuseNode true
                        args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                    }
                }
                steps {
                    sh 'docker compose up --build -d'
                }
              }

              stage ('API Testing') {
                agent {
                    docker {
                        image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
                        alwaysPull true
                        reuseNode true
                        args '-u 0 --network=host'
                    }
                }

                steps {
                    dir('tests-api') {
                        sh 'npm ci'
                        sh 'npx wait-port http://localhost:8081/api/health -t 30000'
                        sh 'npx playwright test'
                    }
                }

                post {
                    always {
                        junit 'tests-api/test-results/results.xml'
                                                publishHTML target: [
                                                    reportDir: 'tests-api/playwright-report',
                                                    reportFiles: 'index.html',
                                                    reportName: 'Playwright API Test Report'
                        ]
                    }
                }
              }
              stage ('E2E Tests') {
                agent {
                    docker {
                         image 'mcr.microsoft.com/playwright:v1.59.1-jammy'
                        alwaysPull true
                        reuseNode true
                        args '-u 0 --network=host'
                    }
                }
                steps {
                    dir ('tests-e2e') {
                        sh 'npm ci'
                        sh 'npx playwright test'
                    }
                }
                post {
                    always {
                        junit 'tests-e2e/test-results/results.xml'
                        publishHTML target: [
                            reportDir: 'tests-e2e/playwright-report',
                            reportFiles: 'index.html',
                            reportName: 'playwright E2E Test report'
                        ]
                    }
                }
              }
            }
         post {
            always {
                cleanWs()
            }
         }
        }             

        
    }
}
