pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                HOME = "${WORKSPACE}"
                GOPATH = "${WORKSPACE}/.go"
                GOMODCACHE = "${WORKSPACE}/.go/pkg/mod"
                XDG_CACHE_HOME = "${WORKSPACE}/.cache"
                GOCACHE = "${WORKSPACE}/.cache/go-build"
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'mkdir -p "$GOPATH" "$GOMODCACHE" "$XDG_CACHE_HOME" "$GOCACHE" && go test ./... -v'
                }
            }
        }
    }
}
